# Site settings
title: Uprising Immobilier
email: ehnouninoun@gmail.com
url: https://nouninoun.github.io/immoup/
description: "Le Site de l'encan immobilier d'Uprising. Tout ce que vous devez savoir sur les lots offerts durant les mises à l'enchère !"
keywords: "Uprising, GTARP, FiveM, Immobilier"
skills: "Immobilier dans l'âme"
meta_author: Alice Wolf Smith

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Immobilier Uprising
  location: Uprising
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://live.uprisingroleplay.com/
  - title: facebook
    url: https://live.uprisingroleplay.com/
  - title: stack-overflow
    url: https://live.uprisingroleplay.com/
  - title: bitbucket
    url: https://live.uprisingroleplay.com/
  - title: github
    url: https://live.uprisingroleplay.com/

# Postal address (add as many lines as necessary)
address:
  - line: PillBox Hill
  - line: Uprising

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
